apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: roboshop
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app2
spec:
  replicas: 2
  selectors:
    matchLabels:
      purpose: ingress-demo
      project: roboshop
      app: app2
  template:
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app2
    spec:
      containers:
      - name: app2
        image: 9959087127/app2:v1

---

apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app2
  ports:
  - protocol: TCP
    port: 80
    targerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  namespace: roboshop
  annotations: 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:247898554458:certificate/0bb04ff4-f447-4f3d-bd27-09458f1bd42a
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb 
  rules:
  - host: "app1.inkweave.dpdns.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2-service
            port:
              number: 80